name: Continuous Integration

on:
  push:
    tags:
      - "v*" # Version tagged pushes
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Run on pinned nightly and latest nightly
        rust: ["", nightly]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy

      - uses: Swatinem/rust-cache@v1

      - name: Clippy is lovely <3
        run: cargo clippy --workspace -- --deny clippy::all

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Run on pinned nightly and latest nightly
        rust: ["", nightly]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Running tests
        run: cargo test --workspace

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          override: true
          components: rustfmt

      - uses: Swatinem/rust-cache@v1

      - name: Checking format
        run: cargo fmt --all -- --check

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [clippy, test, format]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1

      - uses: Swatinem/rust-cache@v1

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --release

      - name: Display checksum
        run: shasum -a 256 target/x86_64-unknown-linux-gnu/release/diary-generator

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-unknown-linux-gnu/release/diary-generator
          generate_release_notes: true
